# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aloc < Formula
  desc "Semantic LOC counter - understand your codebase by role"
  homepage "https://github.com/modern-tooling/aloc"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/modern-tooling/aloc/releases/download/v0.4.0/aloc_0.4.0_darwin_x86_64.tar.gz"
      sha256 "14052b7bece175036bca5502a269ff21dc45bf67e71e103f16b7761a601d2143"
    end
    on_arm do
      url "https://github.com/modern-tooling/aloc/releases/download/v0.4.0/aloc_0.4.0_darwin_arm64.tar.gz"
      sha256 "193d07c545a82d92caa202f1fd33fcc917b899526cc85cac4e6f1a80cce93b66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/modern-tooling/aloc/releases/download/v0.4.0/aloc_0.4.0_linux_x86_64.tar.gz"
      sha256 "8bd897cc33c27c2671b2ef506d9cc8595cceffc10b05a51898b0897ec4a2e44c"
    end
    on_arm do
      url "https://github.com/modern-tooling/aloc/releases/download/v0.4.0/aloc_0.4.0_linux_arm64.tar.gz"
      sha256 "2129cf41b53354ccbb30e4282ff99a86d3fc173780295dfd40639acabb773db4"
    end
  end

  def install
    bin.install "aloc"
  end

  test do
    system "#{bin}/aloc", "--help"
  end
end
